-- { 
--     CatalogVersion = '1',
--     CustomData = { 
--       power_level = '300',
--       properties = '{"power_vs_large":1,"crit_chance":1}',
--       rarity = 'unique',
--       skin = 'wh_brace_of_pistols_skin_05_runed_01',
--       traits = '["ranged_replenish_ammo_headshot"]' 
--     },
--     ItemId = 'wh_brace_of_pistols',
--     ItemInstanceId = '4F8DEE4AFED2297B',
--     PurchaseDate = '2021-09-29T05:48:31.742Z',
--     RemainingUses = 1,
--     UnitPrice = 0,
--     backend_id = '4F8DEE4AFED2297B',
--     data = { 
--       can_wield = { 'wh_zealot', 'wh_bountyhunter', 'wh_captain' },
--       description = 'wh_brace_of_pistols_skin_01_description',
--       display_name = 'wh_brace_of_pistols_skin_01_name',
--       has_power_level = true,
--       hud_icon = 'weapon_generic_icon_brace_of_pistol',
--       inventory_icon = 'icon_wpn_emp_pistol_01_t1',
--       item_type = 'wh_brace_of_pisols',
--       key = 'wh_brace_of_pistols',
--       left_hand_unit = 
--       'units/weapons/player/wpn_emp_pistol_01_t1/wpn_emp_pistol_01_t1',
--       localized_name = 'Patchwork Pistols',
--       name = 'wh_brace_of_pistols',
--       property_table_name = 'ranged',
--       rarity = 'plentiful',
--       right_hand_unit = 
--       'units/weapons/player/wpn_emp_pistol_01_t1/wpn_emp_pistol_01_t1',
--       skin_combination_table = 'wh_brace_of_pistols_skins',
--       slot_type = 'ranged',
--       template = 'brace_of_pistols_template_1',
--       trait_table_name = 'ranged_ammo' 
--     },
--     key = 'wh_brace_of_pistols',
--     power_level = 300,
--     properties = { 
--       crit_chance = 1,
--       power_vs_large = 1 
--     },
--     rarity = 'unique',
--     skin = 'wh_brace_of_pistols_skin_05_runed_01',
--     traits = { 'ranged_replenish_ammo_headshot' } 
--   }


--   { 
--     CatalogVersion = '1',
--     CustomData = { 
--       power_level = '300',
--       properties = '{"power_vs_chaos":1,"power_vs_armoured":1}',
--       property_index = '24',
--       property_seed = '132487567',
--       rarity = 'unique',
--       skin = 'bw_deus_01_skin_01',
--       trait_index = '3',
--       trait_seed = '1345404487',
--       traits = '["ranged_reduced_overcharge"]' 
--     },
--     ItemId = 'bw_deus_01',
--     ItemInstanceId = '620D345945CD464D',
--     PurchaseDate = '2021-09-07T11:21:18.231Z',
--     RemainingUses = 1,
--     UnitPrice = 0,
--     backend_id = '620D345945CD464D',
--     data = { 
--       can_wield = { 'bw_scholar', 'bw_adept', 'bw_unchained' },
--       description = 'bw_deus_01_description',
--       display_name = 'bw_deus_01_name',
--       has_power_level = true,
--       hud_icon = 'weapon_generic_icon_staff_5',
--       inventory_icon = 'icon_wpn_brw_magmastaff_t1',
--       item_type = 'bw_deus_01',
--       key = 'bw_deus_01',
--       left_hand_unit = 'units/weapons/player/wpn_fireball/wpn_fireball',
--       localized_name = "Enchanter's Coruscation Staff",
--       name = 'bw_deus_01',
--       property_table_name = 'ranged',
--       rarity = 'plentiful',
--       right_hand_unit = 'units/weapons/player/wpn_bw_deus_01/wpn_bw_deus_01',
--       skin_combination_table = 'bw_deus_01_skins',
--       slot_type = 'ranged',
--       template = 'bw_deus_01_template_1',
--       trait_table_name = 'ranged_heat' 
--     },
--     key = 'bw_deus_01',
--     power_level = 300,
--     properties = { 
--       power_vs_armoured = 1,
--       power_vs_chaos = 1 
--     },
--     rarity = 'unique',
--     skin = 'bw_deus_01_skin_01',
--     traits = { 'ranged_reduced_overcharge' } 
--   }


--   { 
--     CatalogVersion = '1',
--     CustomData = { 
--       power_level = '5',
--       rarity = 'default',
--       rewarded_from = 'bless' 
--     },
--     ItemId = 'wh_flail_shield',
--     ItemInstanceId = '33D78D18A06FDD46',
--     PurchaseDate = '2021-12-10T04:58:40.15Z',
--     RemainingUses = 1,
--     UnitPrice = 0,
--     backend_id = '33D78D18A06FDD46',
--     data = { 
--       can_wield = { 'wh_priest' },
--       description = 'wh_flail_shield_skin_01_description',
--       display_name = 'wh_flail_shield_skin_01_name',
--       has_power_level = true,
--       hud_icon = 'hud_icon_default',
--       inventory_icon = 'icon_wpn_wh_flail_shield_skin_01_t1',
--       item_type = 'wh_flail_shield',
--       key = 'wh_flail_shield',
--       left_hand_unit = 'units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1',
--       localized_name = 'Noviciate’s Flail & Shield',
--       name = 'wh_flail_shield',
--       property_table_name = 'melee',
--       rarity = 'plentiful',
--       required_dlc = 'bless',
--       right_hand_unit = 'units/weapons/player/wpn_emp_flail_01_t1/wpn_emp_flail_01_t1',
--       skin_combination_table = 'wh_flail_shield_skins',
--       slot_type = 'melee',
--       template = 'one_handed_flail_shield_template',
--       trait_table_name = 'melee' 
--     },
--     key = 'wh_flail_shield',
--     power_level = 5,
--     rarity = 'default' 
--   }


--   { 
--     CatalogVersion = '1',
--     CustomData = { 
--       power_level = '300',
--       properties = '{"protection_chaos":1,"stamina":1}',
--       rarity = 'unique',
--       traits = '["necklace_no_healing_health_regen"]' 
--     },
--     ItemId = 'necklace_04',
--     ItemInstanceId = 'A15BACEC46B39D5A',
--     PurchaseDate = '2021-12-04T12:37:29.948Z',
--     RemainingUses = 1,
--     UnitPrice = 0,
--     backend_id = 'A15BACEC46B39D5A',
--     data = { 
--       can_wield = { 'bw_scholar', 'bw_adept', 'bw_unchained', 'we_shade', 
--         'we_maidenguard', 'we_waywatcher', 'dr_ironbreaker', 'dr_slayer', 'dr_ranger', 
--         'wh_zealot', 'wh_bountyhunter', 'wh_captain', 'es_huntsman', 'es_knight', 
--         'es_mercenary', 'empire_soldier_tutorial', 'wh_priest', 'dr_engineer', 
--         'we_thornsister', 'es_questingknight' },
--       description = 'description_necklace_04',
--       display_name = 'display_name_necklace_04',
--       has_power_level = true,
--       hud_icon = 'item_icon_necklace_01',
--       inventory_icon = 'icon_necklace_04',
--       item_type = 'necklace',
--       key = 'necklace_04',
--       localized_name = "Lector's Amulet",
--       name = 'necklace_04',
--       property_table_name = 'defence_accessory',
--       rarity = 'plentiful',
--       slot_type = 'necklace',
--       template = 'necklace_template',
--       trait_table_name = 'defence_accessory' 
--     },
--     key = 'necklace_04',
--     power_level = 300,
--     properties = { 
--       protection_chaos = 1,
--       stamina = 1 
--     },
--     rarity = 'unique',
--     traits = { 'necklace_no_healing_health_regen' } 
--   }